backend:
  name: github
  repo: daredoes/sjsupokemonclub-site # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "src/img/uploads" # Folder where user uploaded files should go
public_folder: "img/uploads"

collections: # A list of collections the CMS should be able to edit

  - name: "faq"
    label: "Frequently Asked Questions"
    title: "Frequently Asked Questions"
    folder: "site/content/faq"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Weight", name: "weight", widget: "number", default: 50, required: false}

  - name: "tournament"
    label: "Tournament Results"
    folder: "site/content/tournament"
    create: true
    fields:
      - {label: "Tournament Name", name: "title", widget: "string"}
      - {label: "Tournament Description", name: "body", widget: "markdown", required: false}
      - {label: "Tournament Date", name: "date", widget: "datetime"}
      - name: "results"
        label: "Standings"
        widget: "list"
        required: false
        fields:
          - {label: "Standing Name (e.g. First Place)", name: "title", widget: "string", required: true}
          - {label: "Participant Name", name: "participant", widget: "string", required: true}
          - {label: "Partipant Standing", name: "weight", widget: "number", default: "1", required: true}

  - name: "terms"
    label: "Semester Officers"
    folder: "site/content/terms"
    create: true
    fields:
      - {label: "Semester Title", name: "title", widget: "string"}
      - {label: "Semester Description", name: "body", widget: "markdown", required: false}
      - {label: "First Day of the Semester", name: "date", widget: "datetime"}
      - name: "officers"
        label: "Officers"
        widget: "list"
        required: false
        fields:
          - {label: "Title", name: "title", widget: "string", required: true}
          - {label: "Name", name: "participant", widget: "string", required: true}


  - name: "pages"
    label: "Pages"
    folder: "site/content/pages"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "URL", name: "url", widget: "string"}

  - name: "front_page"
    label: "Front Page Sections"
    folder: "site/content/front_page"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Anchor", name: "anchor", widget: "string", required: true}
      - {label: "Weight", name: "weight", widget: "number", default: 50}

  - name: "index"
    label: "Homepage"
    folder: "site/content"
    create: false
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "URL", name: "url", widget: "string"}
      - name: "section"
        label: "Front Page Content Section"
        widget: "list"
        required: false
        fields:
          - {label: "Title", name: "title", widget: "string", required: true}
          - {label: "Content", name: "body", widget: "markdown", required: false}
          - {label: "Weight", name: "weight", widget: "number", default: "50", required: false}

  - name: "footer"
    label: "Footer Details"
    folder: "site/content/footer"
    create: false
    fields:
      - {label: "Title", name: "title", widget: "string", required: true, default: "main"}
      - {label: "Copyright Info", name: "copyright", widget: "string", required: false}
      - {label: "Footer Slogan", name: "slogan", widget: "string", required: false}
      - name: "icons"
        label: "Social Media Icon"
        widget: "list"
        required: false
        fields:
          - {label: "Service Name", name: "title", widget: "string", required: false}
          - {label: "Service URL", name: "url", widget: "string", required: false}
          - {label: "Service Icon Available Here: https://material.io/icons/", name: "icon", widget: "string", required: false, default: "explore"}
          - {label: "Weight", name: "weight", widget: "number", required: false, default: "0"}
